[package]
edition = "2021"
name = "gisty"
version = "0.1.0"

[lib]
create-type = ["cdylib"]

[dependencies]
rand = "0.8"
rocket = "0.5.0-rc.2"
shuttle-service = {version = "0.10.0", features = ["web-rocket"]}
